// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Rehearse",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Rehearse",
            targets: ["AppModule"],
            bundleIdentifier: "name.shahbain.rehearseApp",
            teamIdentifier: "7C7WV8TT97",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "This app uses the microphone to record and analyze practice presentations."),
                .speechRecognition(purposeString: "This app uses speech recognition to transcribe your recordings and detect filler words.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)